name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up C++ compiler
        run: sudo apt update && sudo apt install g++ -y

      - name: Compile all C++ files
        run: |
          mkdir -p build
          g++ -std=c++17 -Wall -Wextra -o build/app *.cpp

      - name: Run compiled application (optional)
        run: ./build/app
        continue-on-error: true  # prevent workflow failure if app needs user input or fails
